export const RECIPES_FETCHING = 'RECIPES_FETCHING';
export const RECIPES_FETCHING_SUCCESS = 'RECIPES_FETCHING_SUCCESS';
export const RECIPES_FETCHING_FAILURE = 'RECIPES_FETCHING_FAILURE';

export const IS_WIDE_ENOUGH = 'IS_WIDE_ENOUGH';
export const COLLAPSE = 'COLLAPSE';

export const HEALTHY_RECIPES_FETCHING = 'HEALTHY_RECIPES_FETCHING';
export const HEALTHY_RECIPES_FETCHING_SUCCESS =
  'HEALTHY_RECIPES_FETCHING_SUCCESS';
export const HEALTHY_RECIPES_FETCHING_FAILURE =
  'HEALTHY_RECIPES_FETCHING_FAILURE';
export const SPECIAL_DIETS_FETCHING = 'SPECIAL_DIETS_FETCHING';
export const SPECIAL_DIETS_FETCHING_SUCCESS = 'SPECIAL_DIETS_FETCHING_SUCCESS';
export const SPECIAL_DIETS_FETCHING_FAILURE = 'SPECIAL_DIETS_FETCHING_FAILURE';
