export const RECIPES_FETCHING = 'RECIPES_FETCHING';
export const RECIPES_FETCHING_SUCCESS = 'RECIPES_FETCHING_SUCCESS';
export const RECIPES_FETCHING_FAILURE = 'RECIPES_FETCHING_FAILURE';
export const FAVOURITE_RECIPE = 'FAVOURITE_RECIPE';

export const HEALTHY_RECIPES_FETCHING = 'HEALTHY_RECIPES_FETCHING';
export const HEALTHY_RECIPES_FETCHING_SUCCESS =
  'HEALTHY_RECIPES_FETCHING_SUCCESS';
export const HEALTHY_RECIPES_FETCHING_FAILURE =
  'HEALTHY_RECIPES_FETCHING_FAILURE';

export const SPECIAL_DIETS_FETCHING = 'SPECIAL_DIETS_FETCHING';
export const SPECIAL_DIETS_FETCHING_SUCCESS = 'SPECIAL_DIETS_FETCHING_SUCCESS';
export const SPECIAL_DIETS_FETCHING_FAILURE = 'SPECIAL_DIETS_FETCHING_FAILURE';

export const RANDOM_RECIPES_FETCHING = 'RANDOM_RECIPES_FETCHING';
export const RANDOM_RECIPES_FETCHING_SUCCESS =
  'RANDOM_RECIPES_FETCHING_SUCCESS';
export const RANDOM_RECIPES_FETCHING_FAILURE =
  'RANDOM_RECIPES_FETCHING_FAILURE';

export const FIRST_PAGE = 'FIRST_PAGE';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREV_PAGE = 'PREV_PAGE';
export const NEXT_HEALTHY_PAGE = 'NEXT_HEALTHY_PAGE';
export const PREV_HEALTHY_PAGE = 'PREV_HEALTHY_PAGE';
export const NEXT_SPECIAL_PAGE = 'NEXT_SPECIAL_PAGE';
export const PREV_SPECIAL_PAGE = 'PREV_SPECIAL_PAGE';

export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES';

export const ADD_PREFERENCE = 'ADD_PREFERENCE';
export const REMOVE_PREFERENCE = 'REMOVE_PREFERENCE';

export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const RECEIVE_SIGNUP = 'RECEIVE_SIGNUP';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const LOGOUT_USER = 'LOGOUT_USER';

export const REQUEST_AUTHENTICATED = 'REQUEST_AUTHENTICATED';
export const RECEIVE_AUTHENTICATED = 'RECEIVE_AUTHENTICATED';
export const ERROR_AUTHENTICATED = 'ERROR_AUTHENTICATED';
export const REQUEST_FAVORITES = 'REQUEST_FAVORITES';
export const RECEIVE_FAVORITES = 'RECEIVE_FAVORITES';
