export const RECIPES_FETCHING = 'RECIPES_FETCHING';
export const RECIPES_FETCHING_SUCCESS = 'RECIPES_FETCHING_SUCCESS';
export const RECIPES_FETCHING_FAILURE = 'RECIPES_FETCHING_FAILURE';

export const HEALTHY_RECIPES_FETCHING = 'HEALTHY_RECIPES_FETCHING';
export const HEALTHY_RECIPES_FETCHING_SUCCESS =
  'HEALTHY_RECIPES_FETCHING_SUCCESS';
export const HEALTHY_RECIPES_FETCHING_FAILURE =
  'HEALTHY_RECIPES_FETCHING_FAILURE';
export const SPECIAL_DIETS_FETCHING = 'SPECIAL_DIETS_FETCHING';
export const SPECIAL_DIETS_FETCHING_SUCCESS = 'SPECIAL_DIETS_FETCHING_SUCCESS';
export const SPECIAL_DIETS_FETCHING_FAILURE = 'SPECIAL_DIETS_FETCHING_FAILURE';

export const FIRST_PAGE = 'FIRST_PAGE';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREV_PAGE = 'PREV_PAGE';
export const NEXT_HEALTHY_PAGE = 'NEXT_HEALTHY_PAGE';
export const PREV_HEALTHY_PAGE = 'PREV_HEALTHY_PAGE';
export const NEXT_SPECIAL_PAGE = 'NEXT_SPECIAL_PAGE';
export const PREV_SPECIAL_PAGE = 'PREV_SPECIAL_PAGE';
